### ISSUE TITLE
Seems to have a mistake in your paper https://arxiv.org/abs/2310.14558

### ISSUE THREAD

**Issue by wwh0411** [XZhang97666/AlpaCare#4]
In Page 5 Table 2, it seems that the right AVG '53.6' has switched its rightful position with the other value '67.6' at the last row. 
<img width="636" alt="image" src="https://github.com/XZhang97666/AlpaCare/assets/55397039/3b052a67-8b7e-43c9-abc6-700c6253fe9c">

**Comment by XZhang97666** [comment]
Thank you for pointing that out! We have revised the table and will upload the new version shortly.

**Comment by wwh0411** [comment]
Thanks for replying. I think your work has made a great contribution !
